---
# tasks file for docker
- name: Garantir a instalacao do docker
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
- apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Instalar o Docker
  apt: name=docker-ce update_cache=yes state=present 
